# Regenerates test/fixtures/phantom_enrol.an2 with phantom's own record
# builders (loaded from ~/repos/phantom) and small generated images:
#
#     mix run scripts/phantom_enrol.exs test/fixtures/phantom_enrol.an2
dir = Path.expand("~/repos/phantom/lib/phantom/nist")

for f <- ~w(field record type1 type2 type10 type14 type15 file),
    do: Code.require_file("#{f}.ex", dir)

alias Phantom.Nist.{File, Type1, Type2, Type10, Type14, Type15}
alias NistView.Codecs

grey = fn w, h ->
  for y <- 0..(h - 1),
      x <- 0..(w - 1),
      into: <<>>,
      do: <<trunc(128 + 90 * :math.sin(x / 2.5) * :math.cos(y / 3.5))>>
end

rgb = fn w, h ->
  for y <- 0..(h - 1), x <- 0..(w - 1), into: <<>>, do: <<rem(x, 256), rem(y, 256), 128>>
end

{:ok, face} = Codecs.encode_png(rgb.(96, 120), 96, 120, 3)
{:ok, print} = Codecs.encode_png(grey.(128, 96), 128, 96, 1)
wsq = Elixir.File.read!("test/fixtures/synthetic.wsq")

date = ~D[2026-09-29]
common = [src: "PHANTOM", date: date]

type2 =
  Type2.build(0, [
    {3, "PH-TEST-0001"},
    {4, "SYNTHETIC TEST DATA - NOT A REAL PERSON - GENERATED BY PHANTOM"},
    {5, "ENROL"}
  ])

t10 =
  Type10.build(
    1,
    %{data: face, width: 96, height: 120, cga: "PNG", csp: "SRGB"},
    common ++ [pos: "F", sap: 20]
  )

t14a =
  Type14.build(
    2,
    %{data: print, width: 128, height: 96, ppi: 500, cga: "PNG"},
    common ++ [imp: 1, fgp: 1, fct: 2]
  )

t14b =
  Type14.build(
    3,
    %{data: wsq, width: 128, height: 96, ppi: 500, cga: "WSQ20"},
    common ++ [imp: 0, fgp: 15, fct: 2]
  )

t15 =
  Type15.build(
    4,
    %{data: wsq, width: 128, height: 96, ppi: 500, cga: "WSQ20"},
    common ++ [imp: 11, fgp: 22, fct: 2]
  )

records = [type2, t10, t14a, t14b, t15]

type1 =
  Type1.build(Enum.map(records, &{&1.type, &1.idc}),
    tot: "ENROL",
    date: date,
    dai: "PHANTOM",
    ori: "PHANTOM",
    tcn: "PH-TEST-0001-ENROL",
    domain: {"PHANTOM", "1"}
  )

out = hd(System.argv())
Elixir.File.write!(out, File.encode([type1 | records]))
IO.puts("wrote #{out}")
